const Images = {
  almora: require("./Almora.png"),
  bageshwar: require("./Bageshwar.jpg"),
  Dehradun: require("./dehradun.jpg"),
  Nainital: require("./nainital.jpg"),
  Pauri: require("./Pauri.jpg"),
  Uttarkashi: require("./Uttarkashi.jpg"),
  Chamoli: require("./Chamoli.jpg"),
  Tehri: require("./Tehri.jpg"),
  Haridwar: require("./Haridwar.jpg"),
  Rudraprayag: require("./rudrapryag.jpg"),
  Pithoragarh: require("./Pithoragarh.jpg"),
  Champawat: require("./Champawat.jpg"),
  udhamSinghNagar: require("./US-nagar.jpg"),
  Kasar: require("./kasarDevi.jpg"),
  Massourie: require("./Massourie.jpg"),
  NandaDevi: require("./NandaDevi.jpg"),
  Chitai: require("./Chitai.jpg"),
  Jageshwar: require("./jageshwar.jpg"),
  Kausani: require("./kausani.jpg"),
  patalBhuvneshwar: require("./patalBhuvneshwar.jpg"),
  Bagnath: require("./bagnath.jpg"),
  Ranikhet: require("./ranikhet.jpg"),
  Dunagiri: require("./dunagiri.jpg"),
  katarmal: require("./katarmal.jpg"),
  Pindari: require("./pindari.jpg"),
  Nainital: require("./nainital.jpg"),
  Kainchi: require("./kanchi.jpg"),
  Mukteshwar: require("./mukteshwar.jpg"),
  kafni: require("./kafni.jpg"),
  Dharchula: require("./dharchula.jpg"),
  Munsiari: require("./munsyari.jpg"),
  Gangolihat: require("./gangolihat.jpg"),
};
export default Images;
